### ISSUE TITLE
Unable to "npm start"

### ISSUE THREAD

**Issue by JohnHanna86** [auth0/react-flux-jwt-authentication-sample#33]
i followed the steps in the readme file, but unfortunately I could not start the project, here is my error log
btw, while install the packages, I noticed some of them were deprecrated

> cross-env NODE_ENV=development hjs-dev-server

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:3000
    at Object.exports._errnoException (util.js:860:11)
    at exports._exceptionWithHostPort (util.js:883:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at net.js:1379:9
    at GetAddrInfoReqWrap.asyncCallback [as callback](dns.js:63:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete](dns.js:82:10)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "start"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE
npm ERR! auth0-react-sample@1.0.0 start: `cross-env NODE_ENV=development hjs-dev-server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the auth0-react-sample@1.0.0 start script 'cross-env NODE_ENV=development hjs-dev-server'.
npm ERR! This is most likely a problem with the auth0-react-sample package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development hjs-dev-server
npm ERR! You can get their info via:
npm ERR!     npm owner ls auth0-react-sample
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\MyStuff\projects\TagManager\resources\auth0-react-sample-sample\npm-debug.log

C:\MyStuff\projects\TagManager\resources\auth0-react-sample-sample>npm run watch
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run" "watch"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6

npm ERR! missing script: watch
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     C:\MyStuff\projects\TagManager\resources\auth0-react-sample-sample\npm-debug.log

**Comment by zguillen** [comment]
it looks like npm run watch target is broken.  I ran npm build, then npm start and this app is working for me now on localhost:3000
